### PR TITLE
Ensure we wait for apt update before installing package

### PR DESCRIPTION
**Pull request by gabriel403**

### CODE REVIEW

**Comment by MNiedzielski** [comment]
Sskk#

K

On Wed, Aug 17, 2016 at 6:31 AM, Gabriel Baker < notifications@github.com [notifications@github.com] > wrote:

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/fsalum/puppet-newrelic/pull/65 [https://github.com/fsalum/puppet-newrelic/pull/65]

COMMIT SUMMARY
- Ensure we wait for apt update before installing package

FILE CHANGES
- M manifests/agent/php.pp [https://github.com/fsalum/puppet-newrelic/pull/65/files#diff-0](6)

PATCH LINKS:
- https://github.com/fsalum/puppet-newrelic/pull/65.patch [https://github.com/fsalum/puppet-newrelic/pull/65.patch]
- https://github.com/fsalum/puppet-newrelic/pull/65.diff [https://github.com/fsalum/puppet-newrelic/pull/65.diff]

**Comment by YarNhoj** [comment]
@gabriel403 Puppet wants a default on the case statements you are providing. Should we be using an if statement here instead?

**Comment by gabriel403** [comment]
@YarNhoj ah good point, I'll switch it to an if!

**Comment by gabriel403** [comment]
@YarNhoj done!

**Comment by YarNhoj** [comment]
@gabriel403 I didn't forget you. Just been traveling! Let me look at why this build is failing.

**Pull request closed without merging**
